### ISSUE TITLE
Site refers to `setup.sh` instead of `setup.sql`

### ISSUE THREAD

**Issue by andrewwylde** [dwmkerr/node-docker-microservice#1]
[On the walkthrough](http://www.dwmkerr.com/learn-docker-by-building-a-microservice) under Step 1 it talks about `setup.sh` when it should be `setup.sql`. Might be confusing to some who are blind typers and don't pay attention (like me!).

**Comment by dwmkerr** [comment]
Well spotted @astoellis! Thanks for the heads up, I've fixed the mistake :smile:
