### ISSUE TITLE
Step 1: ERROR 1045 (28000): Access denied for user 'users_service'@'localhost'

### ISSUE THREAD

**Issue by kekemoto** [dwmkerr/node-docker-microservice#12]
I did `git clone`.  
I did `git checkout step1`.  
I did `./start.sh`.

The following was displayed.
```
Starting DB...
2cc0806676b0b73021429f7c57b6186f2437bc9203048729208d95b9efa7705c
Waiting for DB to start up...
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Got error: Access denied for user 'users_service'@'localhost' (using password: YES)
Setting up initial data...
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'users_service'@'localhost' (using password: YES)
```

**Comment by bradley-curran** [comment]
Hey, to fix this I added a 

`sleep 5`

Between each docker command. 

Unfortunately I don't know why this works. It seems that it runs each docker command before the previous command has completely setup.

**Comment by Karl-EdwardJeanMehu** [comment]
I did the above and not only am I getting an access denied error, I'm also getting the following 

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`

Here is what my start.sh file looks like 

`#!/bin/sh

# Run the MySQLl container with the database 'test'
# Along with a services user, 'admin', that can access it
echo 'Starting DB...'
docker run --name db -d \
-e MYSQL_ROOT_PASSWORD=123 \
-e MYSQL_DATABASE=users -e MYSQL_USER=users_service -e MYSQL_PASSWORD=123 \
-p 3306:3306 \
mysql:latest

# wait 10 seconds
sleep 5 

# Wait for database service to start
echo 'Waiting for database to start'
docker exec db mysqladmin --silent --wait=30 -uusers_service -p123 ping || exit 1

sleep 5

# Run setup script
echo 'Loading initial data...'
docker exec -i db mysql -uusers_service -p123 test < setup.sql
`

**Comment by kekemoto** [comment]
Thank you !

**Comment by Karl-EdwardFPJeanMehu** [comment]
Has anyone figured this out?
