### ISSUE TITLE
Rename project from node-docker-mircroservice to https://github.com/dwmkerr/node-docker-microservice

### ISSUE THREAD

**Issue by ElijahLynn** [dwmkerr/node-docker-microservice#2]
The URL of this project is spelled node-docker-mircroservice and should be node-docker-microservice. Github will put a redirect in place if you rename the project.

**Comment by dwmkerr** [comment]
@ElijahLynn thanks! I've got no idea how I missed that! I've made the change.

**Comment by ElijahLynn** [comment]
Nice, you may also want to update the link in the blog, even though the redirect is there.

![image](https://cloud.githubusercontent.com/assets/1504756/15856934/9daad6aa-2c86-11e6-920d-219c8300fc25.png)

**Comment by dwmkerr** [comment]
Done!
